# cronjob to delete readings older than 3 days. runs nightly. just runs psql.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-old-readings
  namespace: sensormon
spec:
  schedule: "0 4 * * *"          # 0400 daily
  concurrencyPolicy: Forbid       # one at a time, please!
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cleanup
              image: postgres:17    # same image
              envFrom:
                - secretRef:
                    name: sensormon-secret
              env:
                - name: TZ
                  value: "America/Los_Angeles"
              command:
                - /bin/sh
                - -c
                - >
                  PGPASSWORD="$POSTGRES_PASSWORD"
                  psql -h postgres -U "$POSTGRES_USER" -d "$POSTGRES_DB"
                  -c "DELETE FROM \"Readings\" WHERE \"Timestamp\" < LOCALTIMESTAMP - interval '3 days';"
